### ISSUE TITLE
Url esta indefinida para todas las consultas

### ISSUE THREAD

**Issue by fabriziotonin** [NicoG72/proyectoFinal#2]
al intentar ingresar con los permisos dados , no puedo acceder revisando la dirección enviada se puede visualizar que la url al que se hace el post recibe como parametro undefined provocando el error 
![image](https://user-images.githubusercontent.com/51201108/132273596-7b72ba24-49e1-47ff-bbd9-2834b7c2aec9.png)

**Comment by canto1380** [comment]
Resuelto. Se actualizo la URL en trello
